### ISSUE TITLE
[Develop] 편의점 카테고리

### ISSUE THREAD

**Issue by dolphin1404** [dolphin1404/GoodMenu_CBNUOS#10]
## Problem
편의점 카테고리를 탭으로 따로 만들어서 사용자가 편하게 찾을 수 있도록 해주세요.
또한 ATM 기기 위치도 추가해주시면 좋을 것 같아요.
@hyuk041023 님이 담당해서 PR 해주세요.

## Task 👍 
- [x] 편의점 카테고리 추가.
- [x]  ATM 기기 위치 추가

**Comment by hyuk041023** [comment]
ATM 기기 위치는 script.js의  "교내시설" 카테고리로 추가하였습니다

**Comment by dolphin1404** [comment]
커밋한 이후 resolve #번호로 pr 올려주세요.

**Comment by dolphin1404** [comment]
> ATM 기기 위치는 script.js의 "교내시설" 카테고리로 추가하였습니다
커밋한 이후 resolve #번호로 pr 올려주세요.

**Comment by dolphin1404** [comment]
> ATM 기기 위치는 script.js의 "교내시설" 카테고리로 추가하였습니다

커밋한 이후 resolve #번호로 pr 올려주세요.
