### ISSUE TITLE
[FEAT] have to make in container

### ISSUE THREAD

**Issue by wootaehyeon** [dolphin1404/GoodMenu_CBNUOS#2]
## 💡 Feature Issue

>네이버 플레이스 페이지를 받아와서 메뉴와 운영시간을 알려주는 container 작성
> 개요 container의 중앙과 오른쪽 

## 🌿  To-do

- [x] add to container naver place address 
- [x] link addresss

**Comment by dolphin1404** [comment]
Resolved. Thanks your contribution. Keep going dude.
